// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(config) {
    return config.set({
      frameworks: ['jasmine'],
      preprocessors: {
        '**/*.coffee': ['coffee']
      },
      coffeePreprocessor: {
        options: {
          bare: true,
          sourceMap: false
        },
        transformPath: function(path) {
          return path.replace(/\.coffee$/, '.js');
        }
      },
      files: ['../storage_or_cookies.js', '*.coffee'],
      browsers: ['Chrome'],
      plugins: ['karma-jasmine', 'karma-coffee-preprocessor', 'karma-chrome-launcher', 'karma-coverage', 'karma-junit-reporter', 'karma-growl'],
      reporters: ['progress', 'junit', 'growl', 'coverage'],
      singleRun: true
    });
  };

}).call(this);

//# sourceMappingURL=karma.conf.map
